Mini_Project/Areas/UserArea/Controllers/ProductController.cs
using Mini_Project.CusAusFilters;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mini_Project.Areas.UserArea.Controllers
{
    [UserCusAus]
    public class ProductController : Controller
    {
        Mini_Project_DbFirstEntities mpd = new Mini_Project_DbFirstEntities();
        // GET: UserArea/Product
        public ActionResult Index()
        {
            ViewBag.ProductID = new SelectList(this.mpd.ProductTbls.ToList(), "ProductID", "ProductName");
            return View(this.mpd.ProductTbls.ToList());
        }
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.ProductID = new SelectList(this.mpd.ProductTbls.ToList(), "ProductID", "ProductName");
            ViewBag.CategoryID = new SelectList(this.mpd.CategoryTbls.ToList(), "CategoryID", "CategoryName");
            ViewBag.MfgID = new SelectList(this.mpd.MfgTbls.ToList(), "MfgID", "MfgName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProductTbl rec, List<Int64> chk)
        {
            this.mpd.ProductTbls.Add(rec);
            foreach(var temp in chk)
            {
                ProductColorTbl pcrec=new ProductColorTbl();
                pcrec.ColorID = temp;
                pcrec.ProductID = temp;
                this.mpd.ProductColorTbls.Add(pcrec);
            }
            this.mpd.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(Int64? id)
        {
            var rec = this.mpd.ProductTbls.Find(id);
            ViewBag.CategoryID = new SelectList(this.mpd.CategoryTbls.ToList(), "CategoryID", "CategoryName",rec.CategoryID);
            ViewBag.MfgID = new SelectList(this.mpd.MfgTbls.ToList(), "MfgID", "MfgName",rec.MfgID);
            ViewBag.ProductID = new SelectList(this.mpd.ProductTbls.ToList(), "ProductID", "ProductName");
            return View(rec);
        }
        [HttpPost]
        public ActionResult Edit(ProductTbl rec, List<Int64> chk)
        {
            var oldcolor = this.mpd.ProductColorTbls.Where(p => p.ProductID == rec.ProductID);
            
            foreach(var temp in oldcolor)
            {
                this.mpd.ProductColorTbls.Remove (temp); 
            }
            var oldrec = this.mpd.ProductTbls.Find(rec.ProductID);
            oldrec.ProductName = rec.ProductName;
            oldrec.MfgID = rec.MfgID;
            oldrec.Price = rec.Price;
            oldrec.ProductDescription=rec.ProductDescription;
            oldrec.CategoryID = rec.CategoryID;

            foreach(var temp in chk)
            {
                ProductColorTbl pcrec=new ProductColorTbl();
                pcrec.ColorID = temp;
                pcrec.ProductID = rec.ProductID;
                this.mpd.ProductColorTbls.Add(pcrec);
            }
            this.mpd.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Details(Int64? id)
        {
           var rec= this.mpd.ProductTbls.Find(id);
           return View(rec);
        }
        public ActionResult Delete(Int64? id)
        {
            var procolor = this.mpd.ProductColorTbls.Where(p => p.ProductID == id);
            foreach(var temp in procolor)
            {
                this.mpd.ProductColorTbls.Remove(temp);
            }

            var rec=this.mpd.ProductTbls.Find(id);
            this.mpd.ProductTbls.Remove(rec);
            this.mpd.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Mini_Project/Controllers/CheckBoxListController.cs
using Mini_Project.Areas.UserArea;
using Mini_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mini_Project.Controllers
{
    public class CheckBoxListController : Controller
    {
        // GET: CheckBoxList
        Mini_Project_DbFirstEntities mpd=new Mini_Project_DbFirstEntities();
        
        public ActionResult GenerateCheckBoxList(Int64 id=0)
        {
            if (id == 0)
            {
                //first we have to load all colors

                var allcolors = from m in this.mpd.ColorTbls
                                select new CheckBoxVM
                                {
                                    Value=m.ColorID,
                                    Text=m.ColorName,
                                    IsSelected=false,
                                };
                return PartialView("CheckBoxListPartial", allcolors);
            }
            {
                //here we have to load all colors which belongs to the productid

                var allcolors = from m in this.mpd.ColorTbls
                                select new CheckBoxVM
                                {
                                    Value=m.ColorID,
                                    Text=m.ColorName,
                                    IsSelected=this.mpd.ProductColorTbls.Any(p=>p.ColorID==m.ColorID)
                                };
                return PartialView("CheckBoxListPartial",allcolors);
            }

        }
    }
}

Mini_Project/Areas/UserArea/Views/Product/Create.cshtml
@model Mini_Project.Areas.UserArea.ProductTbl
@{
    Layout = "~/Areas/UserArea/Views/Shared/_LayoutPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div>
        @using (Html.BeginForm())
        {
            <div>
                @Html.LabelFor(p => p.ProductName)
                <div>
                    @Html.EditorFor(p => p.ProductName)
                </div>
            </div>
            <div>
                @Html.Label("Select MfgName")
                <div>
                    @Html.DropDownList("MfgID", "Select MfgName")
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.Price)
                <div>
                    @Html.EditorFor(p => p.Price)
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.ProductDescription)
                <div>
                    @Html.EditorFor(p => p.ProductDescription)
                </div>
            </div>
            <div>
                @Html.Label("Select Category")
                <div>
                    @Html.DropDownList("CategoryID", "Select Category Name")
                </div>
            </div>
           <div>
               @Html.Action("GenerateCheckBoxList", "CheckBoxList", new { area = "" })
           </div>
           <br />
            <div>
                <input type="submit" value="Save" />
            </div>
        }
        <div>
            @Html.ActionLink("Back to Index", "Index")
        </div>
    </div>
</body>
</html>

Mini_Project/Areas/UserArea/Views/Product/Details.cshtml
@model  Mini_Project.Areas.UserArea.ProductTbl
@{
    Layout = "~/Areas/UserArea/Views/Shared/_LayoutPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2> Product Details </h2>
    <div>
        <dl>
          <div>
                @Html.DisplayNameFor(p=>p.ProductName):
                @Html.DisplayFor(p=>p.ProductName)
            </div>

          <div>
              @Html.DisplayNameFor(p => p.Price):
              @Html.DisplayFor(p => p.Price)
          </div>
          <div>
              @Html.DisplayNameFor(p => p.ProductDescription):
              @Html.DisplayFor(p => p.ProductDescription)
          </div>

          <div>
              @Html.DisplayNameFor(p => p.CategoryTbl.CategoryName):
              @Html.DisplayFor(p => p.CategoryTbl.CategoryName)
          </div>
          <div>
              @Html.DisplayNameFor(p => p.MfgTbl.MfgName):
              @Html.DisplayFor(p => p.MfgTbl.MfgName)
          </div>
            <div>
                @Html.Label("Product Colors:")
                @foreach(var temp in Model.ProductColorTbls)
            {
                <span>
                    @temp.ColorTbl.ColorName
                </span>
            }
            </div>
        </dl>
        <div>
            @Html.ActionLink("Back to Index", "Index")
        </div>
    </div>
</body>
</html>

Mini_Project/Areas/UserArea/Views/Product/Edit.cshtml
@model Mini_Project.Areas.UserArea.ProductTbl
@{
    Layout = "~/Areas/UserArea/Views/Shared/_LayoutPage1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body >
    <div>
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(p => p.ProductID)
            <div>
                @Html.LabelFor(p => p.ProductName)
                <div>
                    @Html.EditorFor(p => p.ProductName)
                </div>
            </div>
            <div>
                @Html.Label("Select MfgName")
                <div>
                    @Html.DropDownList("MfgID", "Select MfgName")
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.Price)
                <div>
                    @Html.EditorFor(p => p.Price)
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.ProductDescription)
                <div>
                    @Html.EditorFor(p => p.ProductDescription)
                </div>
            </div>
            <div>
                @Html.Label("Select Category")
                <div>
                    @Html.DropDownList("CategoryID", "Select Category")
                </div>
            </div>
            <div>
                @Html.Action("GenerateCheckBoxList", "CheckBoxList", new { id = Model.ProductID, area = "" })
            </div>
            <div>
                <input type="submit" value="Update" />
            </div>
        }
        <div>
            @Html.ActionLink("Back to Index", "Index")
        </div>
    </div>
</body>
</html>

Mini_Project/Areas/UserArea/Views/Product/Index.cshtml
@model IEnumerable<Mini_Project.Areas.UserArea.ProductTbl>
@{
    Layout = "~/Areas/UserArea/Views/Shared/_LayoutPage1.cshtml";
    int SrNo = 1;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
   
</head>
<body>
    @Html.ActionLink("Add New", "Create", new {area="UserArea"})
    <div> 
        <table border="1">
            <thead>
                <tr>
                    <th> Sr.No </th>
                    <th> @Html.DisplayNameFor(p=>p.ProductName) </th>
                    <th> @Html.DisplayNameFor(p=>p.MfgTbl.MfgName) </th>
                    <th> @Html.DisplayNameFor(p=>p.Price) </th>
                    <th> @Html.DisplayNameFor(p=>p.ProductDescription) </th>
                    <th> @Html.DisplayNameFor(p=>p.CategoryTbl.CategoryName) </th>
                    <th> Action Links </th>
                </tr>
            </thead>

            @foreach(var temp in Model)
            {
                <tr>
                    <td> @(SrNo++)</td>
                    <td> @Html.DisplayFor(p=>temp.ProductName) </td>
                    <td> @Html.DisplayFor(p=>temp.MfgTbl.MfgName) </td>
                    <td> @Html.DisplayFor(p=>temp.Price) </td>
                    <td> @Html.DisplayFor(p=>temp.ProductDescription) </td>
                    <td> @Html.DisplayFor(p=>temp.CategoryTbl.CategoryName) </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit",new {id=temp.ProductID})
                        @Html.ActionLink("Details", "Details", new {id=temp.ProductID})
                        @Html.ActionLink("Delete","Delete",new {id=temp.ProductID})
                    </td>
                </tr>
            }
        </table>
    </div>
</body>
</html>