Mini_Project/Controllers/ManageUserController.cs
using Mini_Project.Areas.UserArea;
using Mini_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Mini_Project.Controllers
{
    public class ManageUserController : Controller
    {
        // GET: ManageUser

        Mini_Project_DbFirstEntities mpd = new Mini_Project_DbFirstEntities();

        [HttpGet]
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(LoginVM rec)
        {
            var urec = this.mpd.UserTbls.SingleOrDefault(p => p.EmailID==rec.EmailID && p.Password == rec.Password);
            if (urec != null)
            {
                Session["UserID"] = urec.UserID;
                Session["FirstName"] = urec.FirstName;
                return RedirectToAction("Home", "UserHome", new { area = "UserArea" });
            }
            ModelState.AddModelError("", "Invalid EmailID or Password");
            return View(rec);
        }
        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignUp(UserVM rec)
        {
                if (ModelState.IsValid)
            {
                UserTbl urec = new UserTbl();
                urec.FirstName = rec.FirstName;
                urec.LastName = rec.LastName;
                urec.Address = rec.Address;
                urec.EmailID = rec.EmailID;
                urec.MobileNo = rec.MobileNo;
                urec.Password = rec.Password;
                this.mpd.UserTbls.Add(urec);
                this.mpd.SaveChanges();

                return RedirectToAction("SignIn");
            }

            return View(rec);
        }
        [HttpGet]
        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();

            return RedirectToAction("SignIn");
        }

    }
}

Mini_Project/Views/ManageUser/LogOut.cshtml
@{
    Layout = "~/Areas/UserArea/Views/Shared/_LayoutPage1.cshtml";
}

<!DOCTYPE html>

<html style="background-color:antiquewhite;text-align:center;">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LogOut</title>
</head>
<body>
    <div>
        <h1 style="color:deepskyblue;border: thick solid;text-align:center;border-color:black;"> You are logged out succesfully....! </h1>
        @Html.ActionLink("Click Here To SignIn", "SignIn", "ManageUser",new {area=""})
    </div>
</body>
</html>

Mini_Project/Views/ManageUser/SignIn.cshtml
@model Mini_Project.Models.LoginVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html style="border: thick solid; border-color: crimson;background-color:antiquewhite;text-align:center;">
<head>
    <meta name="viewport" content="width=device-width" />
    <title> SignIn </title>
</head>
<body >
    <h1> SignIn </h1>
    <div> 
        @using (Html.BeginForm())
            {
            <div>
                @Html.ValidationSummary(true)
            </div>
                <div>
                    @Html.LabelFor(p=>p.EmailID)
                    <div>
                        @Html.EditorFor(p=>p.EmailID) <br />
                        @Html.ValidationMessageFor(p=>p.EmailID)
                    </div>
                </div>
                <div>
                    @Html.LabelFor(p=>p.Password)
                    <div>
                        @Html.EditorFor(p=>p.Password) <br />
                        @Html.ValidationMessageFor(p=>p.Password)
                    </div>
                </div>
                <div>
                    EmailID:suresh@gmail.com <br />
                    Password:abc
                </div>
                <div>
                    <input type="submit" value="SignIn" />
                    @Html.ActionLink("Click Here To Register","SignUp","ManageUser")
                </div>
            }
    </div>
</body>
</html>

Mini_Project/Views/ManageUser/SignUp.cshtml
@model Mini_Project.Models.UserVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html style="border: thick solid; border-color: crimson;background-color:antiquewhite;text-align:center;">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SignUp</title>
</head>
<body>
    <h1> Register New User </h1>
    <div>
        @using (Html.BeginForm())
        {
           
            <div>
                @Html.ValidationSummary(true)
            </div>
            <div>
                @Html.LabelFor(p => p.FirstName)
                <div>
                    @Html.EditorFor(p => p.FirstName) <br />
                    @Html.ValidationMessageFor(p => p.FirstName)
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.LastName)
                <div>
                    @Html.EditorFor(p => p.LastName) <br />
                    @Html.ValidationMessageFor(p => p.LastName) 
                </div>
            </div> 
            <div>
                @Html.LabelFor(p => p.Address)
                <div>
                    @Html.EditorFor(p => p.Address) <br />
                    @Html.ValidationMessageFor(p => p.Address)
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.EmailID)
                <div>
                    @Html.EditorFor(p => p.EmailID) <br />
                    @Html.ValidationMessageFor(p => p.EmailID)
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.MobileNo)
                <div>
                    @Html.EditorFor(p => p.MobileNo) <br />
                    @Html.ValidationMessageFor(p => p.MobileNo)
                </div>
            </div>
            <div>
                @Html.LabelFor(p => p.Password)
                <div>
                    @Html.EditorFor(p => p.Password) <br />
                    @Html.ValidationMessageFor(p => p.Password)
                </div>
            </div>
            <div>
                <input type="submit" value="Save" />
                @Html.ActionLink("Click here to SignIn", "SignIn")
            </div>
        }
    </div>
</body>
</html>